install.packages('data.table')
install.packages('devtools')
install.packages('flexdashboard')
install.packages('ggplot2')
install.packages('tictoc')
install.packages('plotly')
devtools::install_github("r-arduino/arduinor")
